version: '3.8'

services:
  tts-service:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/learning-platform/tts-service:latest
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    environment:
      - KAFKA_BROKERS=10.0.10.10:9092,10.0.10.11:9092,10.0.10.12:9092
      - S3_BUCKET=tts-service-storage
      - AWS_REGION=us-east-1
    networks:
      - learning-network
    ports:
      - "5001:5001"

  stt-service:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/learning-platform/stt-service:latest
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    environment:
      - KAFKA_BROKERS=10.0.10.10:9092,10.0.10.11:9092,10.0.10.12:9092
      - S3_BUCKET=stt-service-storage
      - AWS_REGION=us-east-1
    networks:
      - learning-network
    ports:
      - "5002:5002"

  chat-service:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/learning-platform/chat-service:latest
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    environment:
      - KAFKA_BROKERS=10.0.10.10:9092,10.0.10.11:9092,10.0.10.12:9092
      - S3_BUCKET=chat-service-storage
      - AWS_REGION=us-east-1
    networks:
      - learning-network
    ports:
      - "5003:5003"

  document-reader-service:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/learning-platform/document-reader-service:latest
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    environment:
      - KAFKA_BROKERS=10.0.10.10:9092,10.0.10.11:9092,10.0.10.12:9092
      - S3_BUCKET=document-reader-storage
      - AWS_REGION=us-east-1
    networks:
      - learning-network
    ports:
      - "5004:5004"

  quiz-service:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/learning-platform/quiz-service:latest
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    environment:
      - KAFKA_BROKERS=10.0.10.10:9092,10.0.10.11:9092,10.0.10.12:9092
      - S3_BUCKET=quiz-service-storage
      - AWS_REGION=us-east-1
    networks:
      - learning-network
    ports:
      - "5005:5005"

networks:
  learning-network:
    driver: overlay
    attachable: true
